'use client';

import { ArrowRight, Bot, Compass, Landmark, MessageSquare } from 'lucide-react';
import type { AppMode, ChatMessage, SlideData } from './types';

interface ContentPanelProps {
  appMode: AppMode;
  chatMessages: ChatMessage[];
  chatScrollRef: React.RefObject<HTMLDivElement | null>;
  activeSlideNode: SlideData | null;
  currentNodeIndex: number;
  route?: { destination?: string; slides?: SlideData[] } | null;
  getAssetUrl: (url: string) => string;
  fallbackPlaceholder: string;
}

export default function ContentPanel({ appMode, chatMessages, chatScrollRef, activeSlideNode, currentNodeIndex, route, getAssetUrl, fallbackPlaceholder }: ContentPanelProps) {
  return (
    <div className="relative flex h-full w-1/2 items-center justify-center overflow-hidden bg-zinc-950 p-6">
      <div className="relative flex h-full w-full flex-col overflow-hidden rounded-2xl border border-zinc-900 bg-zinc-950/80 shadow-2xl">
        {appMode === 'chat' && <div className="flex h-full flex-col"><div className="flex items-center gap-2 border-b border-zinc-900 p-4"><MessageSquare className="size-4 text-cyan-400" /><span className="font-mono text-xs uppercase tracking-widest text-zinc-400">Conversation</span></div><div ref={chatScrollRef} className="flex-1 space-y-4 overflow-y-auto p-6">{chatMessages.length === 0 ? <div className="flex h-full flex-col items-center justify-center p-8 text-center"><Bot className="mb-4 size-12 text-zinc-800" /><p className="max-w-xs text-sm leading-relaxed text-zinc-500">Press the microphone and start talking. Ask me about rooms, facilities, or just chat!</p><p className="mt-3 font-mono text-xs text-zinc-700">Try: &quot;Where is the ICT Lab?&quot; or &quot;What&apos;s on the first floor?&quot;</p></div> : chatMessages.map((msg, index) => <div key={`${msg.timestamp}-${index}`} className={`message-enter flex ${msg.role === 'user' ? 'justify-end' : 'justify-start'}`}><div className={`flex max-w-[85%] gap-3 ${msg.role === 'user' ? 'flex-row-reverse' : 'flex-row'}`}><div className={`flex size-8 shrink-0 items-center justify-center rounded-full ${msg.role === 'user' ? 'bg-cyan-600' : 'border border-zinc-700 bg-zinc-800'}`}>{msg.role === 'user' ? <span className="text-xs text-white">You</span> : <Bot className="size-4 text-cyan-400" />}</div><div className={`rounded-2xl border px-4 py-3 text-[13px] leading-relaxed ${msg.role === 'user' ? 'border-cyan-600/30 bg-cyan-600/20 text-cyan-100' : 'border-zinc-800 bg-zinc-900 text-zinc-300'}`}>{msg.content}</div></div></div>)}</div></div>}
        {appMode === 'navigation' && <div className="flex h-full w-full flex-col"><div className="relative flex w-full flex-1 items-center justify-center overflow-hidden bg-zinc-900/40">{activeSlideNode ? activeSlideNode.video ? <video src={getAssetUrl(activeSlideNode.video)} className="h-full w-full object-cover opacity-90 transition-all duration-500" autoPlay loop muted playsInline preload="auto" key={`slide-frame-${currentNodeIndex}`} /> : <div className="flex h-full w-full items-center justify-center bg-zinc-950 text-center text-sm text-zinc-400">No video clip available for this step.</div> : <div className="absolute inset-0 flex flex-col items-center justify-center gap-3 bg-zinc-950"><div className="size-8 animate-spin rounded-full border-4 border-cyan-500/30 border-t-cyan-400" /><span className="font-mono text-xs tracking-wider text-zinc-400">Calculating route...</span></div>}<div className="absolute left-4 right-4 top-4 flex items-center justify-between gap-4 rounded-xl border border-zinc-800 bg-zinc-950/90 p-3 shadow-xl backdrop-blur-md"><div className="flex min-w-0 flex-col gap-0.5"><span className="flex items-center gap-1.5 font-mono text-[9px] font-bold uppercase tracking-widest text-cyan-400"><Compass className="size-2.5 animate-pulse text-cyan-400" /> Active Navigation</span><span className="truncate text-xs font-bold text-white">{activeSlideNode ? activeSlideNode.stepTitle : `Heading to ${route?.destination || '...'}`}</span></div>{activeSlideNode?.isLandmark && <div className="flex shrink-0 items-center gap-1 rounded-lg border border-purple-500/30 bg-purple-500/10 px-2.5 py-1 font-mono text-[10px] text-purple-400"><Landmark className="size-3" /> {activeSlideNode.landmarkType?.toUpperCase() || 'LANDMARK'}</div>}</div></div>{route?.slides && currentNodeIndex >= 0 && <div className="flex w-full items-center justify-between border-t border-zinc-900 bg-zinc-950 px-6 py-4 shadow-2xl"><div className="flex max-w-[40%] min-w-0 flex-col truncate"><span className="font-mono text-[10px] font-bold uppercase tracking-wider text-zinc-500">Destination</span><span className="truncate text-xs font-bold text-zinc-300">{route.destination}</span></div><div className="flex max-w-[60%] items-center gap-1.5 overflow-x-auto py-1 pl-2">{route.slides.map((slide, index) => <div key={slide.id || index} className="flex shrink-0 items-center"><div title={slide.stepTitle} className={`size-3 cursor-help rounded-full transition-all duration-300 ${index === currentNodeIndex ? 'scale-125 bg-cyan-400 ring-4 ring-cyan-500/20' : index < currentNodeIndex ? 'bg-emerald-500' : 'bg-zinc-800'}`} />{index < route.slides!.length - 1 && <ArrowRight className="mx-1 size-3 shrink-0 text-zinc-700" />}</div>)}</div></div>}</div>}
        {appMode === 'idle' && <div className="flex h-full flex-col items-center justify-center p-8 text-center"><div className="mb-6 flex size-20 items-center justify-center rounded-full border border-zinc-800 bg-zinc-900"><Compass className="size-10 text-zinc-700" /></div><h2 className="mb-2 text-xl font-bold text-white">Welcome to NaviSense</h2><p className="mb-6 max-w-sm text-sm leading-relaxed text-zinc-500">I&apos;m your conversational building guide. Tap the microphone and speak naturally. Ask for directions, building info, or just say hello!</p><div className="flex flex-col gap-2 font-mono text-xs text-zinc-600"><span>&quot;Take me to the ICT Lab&quot;</span><span>&quot;What rooms are on the first floor?&quot;</span><span>&quot;Tell me about this building&quot;</span></div></div>}
      </div>
    </div>
  );
}
